name:                pixy
version:             0.1.0.0
github:              "githubuser/pixy"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/pixy#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 6 && < 7
- mtl >= 2 && < 3
- pretty >= 1.1 && < 1.2
- containers >= 0.5 && < 0.6

default-extensions:
- TupleSections
- LambdaCase
- MultiWayIf
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- ViewPatterns

library:
    source-dirs:         src

executables:
  pixy-exe:
    main:                Main.hs
    source-dirs:         main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pixy


tests:
  pixy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pixy
    - hspec >= 2 && < 3
    - directory
